// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/626e017a3f133990b78eea96
###
GET http://localhost:8080/contacts/626e017a3f133990b78eea97
###
GET http://localhost:8080/contacts/622023f642f9ab4cd6e060b4
###
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Don",
  "email": "jdon@test.com",
  "favoriteColor": "White",
  "birthday": "1980/01/01"
}
### Test Missing Values
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "lastName": "Don",
  "email": "jdon@test.com",
  "birthday": "1980/01/01"
}
###
PUT http://localhost:8080/contacts/62773bca4b71f495e99a5451 HTTP/1.1
Content-Type: application/json

{
  "firstName": "UpdatedJoe",
  "lastName": "Don",
  "email": "jdon@test.com",
  "favoriteColor": "White",
  "birthday": "1987/03/09"
}
###
DELETE http://localhost:8080/contacts/62773b8e4b71f495e99a5450


// PRODUCTION Deploy
###
GET https://fathomless-mountain-23773.herokuapp.com/contacts
###
GET https://fathomless-mountain-23773.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://fathomless-mountain-23773.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://fathomless-mountain-23773.herokuapp.com/contacts/622023f642f9ab4cd6e060b4

###
POST https://fathomless-mountain-23773.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Don",
  "email": "jdon@test.com",
  "favoriteColor": "White",
  "birthday": "1980/01/01"
}
### Test Missing Values
POST https://fathomless-mountain-23773.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

{
  "lastName": "Don",
  "email": "jdon@test.com",
  "birthday": "1980/01/01"
}
###
PUT https://fathomless-mountain-23773.herokuapp.com/contacts/62773bca4b71f495e99a5451 HTTP/1.1
Content-Type: application/json

{
  "firstName": "UpdatedJoe",
  "lastName": "Don",
  "email": "jdon@test.com",
  "favoriteColor": "White",
  "birthday": "1987/03/09"
}
###
DELETE https://fathomless-mountain-23773.herokuapp.com/contacts/62773b8e4b71f495e99a5450